name: Workflow for CD Delivery for Testers with GitHub Actions

on:
    release:
        types: [published]
    workflow_dispatch: # Trigger the workflow manually
            
env:
    # These secrets must be created in the GitHub repository 
    # Go to your GitHub repository - Go to Settings - Select Actions secrets - Create  

    REGISTRY: ghcr.io # GitHub Container Registry  
    IMAGE_NAME: ${{ github.actor }}/lankapc_ecom_docker_image:latest

jobs:
    Deploy:
        name: Deliver Docker image to Container Registry
        runs-on: ubuntu-latest

        # Add rights to create image on registry
        permissions:
          packages: write
          contents: read
          attestations: write
          id-token: write

        steps:
          - name: Checkout Code
            uses: actions/checkout@v4

          - name: Install Node
            uses: actions/setup-node@v4
            with:
              node-version: 20.x

          - name: Install Dependencies
            run: npm install

          - name: Build Project
            run: npm run build

          - name: Log in to the Container Registry 
            uses: docker/login-action@v2 # Updated to latest version
            with:
              registry: ${{ env.REGISTRY }}  
              username: ${{ github.actor }} 
              password: ${{ secrets.GITHUB_TOKEN }}
              
          - name: Extract Metadata for Docker
            id: meta
            uses: docker/metadata-action@v4 # Updated to latest version
            with:
              images: ${{ env.REGISTRY }}/${{ github.actor }}/lankapc_ecom_docker_image # Ensure the name is lowercase

          - name: Publish
            run: |
                docker build . --tag ${{ env.REGISTRY }}/${{ github.actor }}/lankapc_ecom_docker_image:latest
                docker push ${{ env.REGISTRY }}/${{ github.actor }}/lankapc_ecom_docker_image:latest
